import {beforeAll,expect,it} from 'vitest';
import {readFile} from 'node:fs/promises';
import {renderToStaticMarkup} from 'react-dom/server';
import {load} from 'cheerio';
import ExcelJS from 'exceljs';
import {normalizeRegionalDetails} from '../scripts/sources/regional-details';
import {RegionalDetail} from '../src/components/RegionalDetail';
import type {RegionalDetail as Detail} from '../src/types/statistics';
let data:Record<string,Detail>;let inputs:Buffer[];
beforeAll(async()=>{inputs=await Promise.all(['census-regional-ages.xlsx','vital-final-2025.xlsx','regional-domestic-2025.xlsx','regional-international-2025.xlsx'].map(f=>readFile(`tests/fixtures/${f}`)));data=await normalizeRegionalDetails(inputs[0],inputs[1],inputs[2],inputs[3],Date.parse('2026-10-03T00:00:00+09:00'));});
it('47都道府県の同一基準日の男女・年齢階級と最新年実績',()=>{expect(Object.keys(data)).toHaveLength(47);expect(data['01'].annual.japanese.birth).toBe(21802);expect(data['01'].annual.japanese.death).toBe(74885);for(const d of Object.values(data)){expect(d.populationSource.sourcePeriod).toBe('2025-10');expect(d.annual.year).toBe(2025);for(const group of ['total','japanese','foreign']){const r=d.rows.filter(r=>r.group===group&&r.age==='総数');expect(r.find(r=>r.sex==='男')!.value+r.find(r=>r.sex==='女')!.value).toBe(r.find(r=>r.sex==='男女計')!.value);}}});
it('県内移動・職権消除を除き他県と国外の移動を収録',()=>{expect(data['01'].annual.migration.total).toEqual({domesticIn:53656,domesticOut:58818,internationalIn:22807,internationalOut:15401});for(const key of ['domesticIn','domesticOut','internationalIn','internationalOut'] as const)expect(data['13'].annual.migration.japanese[key]+data['13'].annual.migration.foreign[key]).toBe(data['13'].annual.migration.total[key]);});
it('年や列の変更を拒否し不完全なデータを公開しない',async()=>{const w=new ExcelJS.Workbook();await w.xlsx.load(inputs[2] as never);w.worksheets[0].getCell(8,4).value='2024年';await expect(normalizeRegionalDetails(inputs[0],inputs[1],await w.xlsx.writeBuffer() as unknown as Uint8Array,inputs[3],Date.now())).rejects.toThrow('年が不一致');});
it('過去確定値と同じ開閉UIで6項目を順番に表示し、内訳は付けない',()=>{const $=load(renderToStaticMarkup(<RegionalDetail data={data['01']} group="total" name="北海道"/>));expect($('.official-pyramid>summary').text()).toBe('人口ピラミッド');expect($('.annual-vital').attr('open')).toBeUndefined();expect($('.card-heading').map((_,e)=>$(e).text()).get()).toEqual(['出生確定値','死亡確定値','転入確定値','転出確定値','婚姻確定値','離婚確定値']);expect($('.inflow .event-value').text()).toBe('76,463人');expect($('.outflow .event-value').text()).toBe('74,219人');expect($('.event-breakdown')).toHaveLength(0);});
it('外国人に日本人の出生等を流用せず、移動と人口は外国人の値',()=>{const $=load(renderToStaticMarkup(<RegionalDetail data={data['01']} group="foreign" name="北海道"/>));expect($('.birth .event-value').text()).toBe('データなし');expect($('.death .event-value').text()).toBe('データなし');expect($('.inflow .event-value').text()).not.toBe('データなし');});
