import type { EventKind, EventModel, YearTotal, DisplayPeriod } from '../types/statistics';
import { estimatePeriod } from '../lib/estimate';
import { intervalLabel, number } from '../lib/formatting';
const LABELS = { birth: ['出生', 'BIRTHS', '人', '↗'], death: ['死亡', 'DEATHS', '人', '↘'], marriage: ['婚姻', 'MARRIAGES', '組', '∞'], divorce: ['離婚', 'DIVORCES', '組', '⇄'] };
export function EventCounter({ kind, model, month, now, period, year, officialLabel }: { kind: EventKind; model?: EventModel; month: string; now: number; period: DisplayPeriod; year?: YearTotal; officialLabel: string }) {
  const [label, en, unit, icon] = LABELS[kind];
  const count = estimatePeriod(model, month, now, period, year);
  return <article className={`stat-card ${kind}`}><div className="card-heading"><span className="event-icon" aria-hidden="true">{icon}</span><span>{label}<small>{en}</small></span><span className="badge">{period === 'year' && year?.officialThrough ? `${officialLabel}＋推計` : '推計'}</span></div><p className="stat-period">{period === 'day' ? '今日ここまで' : period === 'month' ? '今月ここまで' : '今年ここまで'}</p><div className="event-value" aria-live="off">{count === null ? '—' : number(count)}<small>{unit}</small></div>{period === 'year' && year && count !== null && <p className="year-parts">{officialLabel} {number(year.officialCount)}{unit}<br/>推計分 {number(count - year.officialCount)}{unit}</p>}<p className="event-interval">{period === 'year' && '今月のペース：'}{model ? intervalLabel(model.ratePerSecond, unit) : 'この月の推計モデルがありません'}</p><div className="card-bottom"><div><span>今月全体の予測</span><strong>{model ? number(model.estimatedMonthCount) : '—'} <small>{unit}</small></strong></div><div><span>{period === 'year' ? '今月の1日平均' : '1日平均'}</span><strong>{model ? number(model.ratePerSecond * 86400) : '—'} <small>{unit}</small></strong></div></div></article>;
}
